"""Environment variable names for configuration settings."""

# Input file paths
OUTPUT_DIR = 'OUTPUT_DIR'
INPUT_FASTA_FILEPATH = 'INPUT_FASTA_FILEPATH'
INPUT_METADATA_CSV_FILEPATH = 'INPUT_METADATA_CSV_FILEPATH'

# Input metadata
FACILITY_NAME = 'FACILITY_NAME'
ANALYST_NAME = 'ANALYST_NAME'

# Input validation
FASTA_MAX_LENGTH_NT = 'FASTA_MAX_LENGTH_NT'
FASTA_MIN_LENGTH_NT = 'FASTA_MIN_LENGTH_NT'
FASTA_MAX_SEQUENCES = 'FASTA_MAX_SEQUENCES'

# File paths
ALLOWED_LOCI_FILE = 'ALLOWED_LOCI_FILE'
FLAG_DETAILS_CSV_PATH = 'FLAG_DETAILS_CSV_PATH'
PLACEHOLDER_IMG_PATH = 'PLACEHOLDER_IMG_PATH'
TAXONKIT_DATA = 'TAXONKIT_DATA'
TIMESTAMP_FILENAME = 'TIMESTAMP_FILENAME'
ACCESSIONS_FILENAME = 'ACCESSIONS_FILENAME'
TAXONOMY_FILE = 'TAXONOMY_FILE'
QUERY_TITLE_FILE = 'QUERY_TITLE_FILE'
HITS_JSON = 'HITS_JSON'
HITS_FASTA = 'HITS_FASTA'
TAXONOMY_ID_CSV = 'TAXONOMY_ID_CSV'
CANDIDATES_FASTA = 'CANDIDATES_FASTA'
PHYLOGENY_FASTA = 'PHYLOGENY_FASTA'
CANDIDATES_CSV = 'CANDIDATES_CSV'
CANDIDATES_JSON = 'CANDIDATES_JSON'
CANDIDATES_COUNT_FILE = 'CANDIDATES_COUNT_FILE'
CANDIDATES_SOURCES_JSON = 'CANDIDATES_SOURCES_JSON'
INDEPENDENT_SOURCES_JSON = 'INDEPENDENT_SOURCES_JSON'
TOI_DETECTED_CSV = 'TOI_DETECTED_CSV'
PMI_MATCH_CSV = 'PMI_MATCH_CSV'
BOXPLOT_IMG_FILENAME = 'BOXPLOT_IMG_FILENAME'
TREE_NWK_FILENAME = 'TREE_NWK_FILENAME'
DB_COVERAGE_JSON = 'DB_COVERAGE_JSON'
LOG_FILENAME = 'LOG_FILENAME'
QUERY_LOG_FILENAME = 'QUERY_LOG_FILENAME'
SQLITE_FILE = 'SQLITE_FILE'
ENTREZ_CACHE_DIRNAME = 'ENTREZ_CACHE_DIRNAME'
ERRORS_DIR = 'ERRORS_DIR'
TEMP_DIR_NAME = 'TEMP_DIR_NAME'

# BLAST configuration
BLAST_MAX_TARGET_SEQS = 'BLAST_MAX_TARGET_SEQS'

# BOLD configuration
BOLD_DATABASE = 'BOLD_DATABASE'
BOLD_FLAG = 'BOLD_FLAG'
BOLD_TAXON_COUNT_JSON = 'BOLD_TAXON_COUNT_JSON'
BOLD_TAXON_COLLECTORS_JSON = 'BOLD_TAXON_COLLECTORS_JSON'
BOLD_TAXONOMY_JSON = 'BOLD_TAXONOMY_JSON'

# GBIF configuration
GBIF_LIMIT_RECORDS = 'GBIF_LIMIT_RECORDS'
GBIF_MAX_OCCURRENCE_RECORDS = 'GBIF_MAX_OCCURRENCE_RECORDS'
GBIF_ACCEPTED_STATUS = 'GBIF_ACCEPTED_STATUS'

# Database coverage
DB_COVERAGE_TOI_LIMIT = 'DB_COVERAGE_TOI_LIMIT'
DB_COVERAGE_MAX_CANDIDATES = 'DB_COVERAGE_MAX_CANDIDATES'

# Other configuration
HMMSEARCH_MIN_EVALUE = 'HMMSEARCH_MIN_EVALUE'
FLAG_FILE_TEMPLATE = 'FLAG_FILE_TEMPLATE'
CACHE_TIMEOUT_HOURS = 'CACHE_TIMEOUT_HOURS'
MAX_API_RETRIES = 'MAX_API_RETRIES'
TEMP_CLEAN_AFTER_DAYS = 'TEMP_CLEAN_AFTER_DAYS'

# Analysis criteria
MIN_NT = 'MIN_NT'
MIN_Q_COVERAGE = 'MIN_Q_COVERAGE'
MIN_IDENTITY = 'MIN_IDENTITY'
MIN_IDENTITY_STRICT = 'MIN_IDENTITY_STRICT'
MEDIAN_IDENTITY_WARNING_FACTOR = 'MEDIAN_IDENTITY_WARNING_FACTOR'
MAX_CANDIDATES_FOR_ANALYSIS = 'MAX_CANDIDATES_FOR_ANALYSIS'
MIN_SOURCE_COUNT = 'MIN_SOURCE_COUNT'
DB_COV_MIN_A = 'DB_COV_MIN_A'
DB_COV_MIN_B = 'DB_COV_MIN_B'
DB_COV_RELATED_MIN_A = 'DB_COV_RELATED_MIN_A'
DB_COV_RELATED_MIN_B = 'DB_COV_RELATED_MIN_B'
DB_COV_COUNTRY_MISSING_A = 'DB_COV_COUNTRY_MISSING_A'
PHYLOGENY_MIN_HIT_IDENTITY = 'PHYLOGENY_MIN_HIT_IDENTITY'
PHYLOGENY_MIN_HIT_SEQUENCES = 'PHYLOGENY_MIN_HIT_SEQUENCES'
PHYLOGENY_MAX_HITS_PER_SPECIES = 'PHYLOGENY_MAX_HITS_PER_SPECIES'

# Report configuration
REPORT_TITLE = 'REPORT_TITLE'
REPORT_DEBUG = 'REPORT_DEBUG'
BLAST_DATABASE_NAME = 'BLAST_DATABASE_NAME'
