process EVALUATE_DATABASE_COVERAGE {

    label 'daff_tax_assign'

    tag "$query_folder"

    // Bind external data and writable locations needed by p5_db_coverage.py.
    containerOptions {
        def bind_app_data = System.getProperty('taxodactyl.bind_app_data', '')
        "--bind ${file(params.taxdb)} --bind ${file(params.allowed_loci_file).parent} --bind ${file(params.outdir)}${bind_app_data} --bind ${file(params.temp_root_dir)} --writable-tmpfs"
    }

    input:
    tuple val(query_folder), path(query_folder_path, stageAs: 'db_coverage_input/*') // Query folder name and path
    path(sequences_file) // Copied sequences file
    path(metadata_file) // Metadata file

    output:
    // Main per-query database coverage result.
    tuple val(query_folder),
        path("$query_folder/db_coverage.json"), emit: db_coverage_json // Output: db_coverage.json file
    // Per-query coverage status flags.
    tuple val(query_folder),
        path("$query_folder/5*flag"), emit: db_coverage_flags // Output: flag files
    // Optional coverage map visualizations.
    tuple val(query_folder),
        path("$query_folder/map*png"), emit: db_coverage_maps, optional: true // Output: coverage map PNG files
    // Process run log.
    path("output/${task.ext.log_filename}"), emit: db_coverage_log // Output: log file
    // Optional per-query error files generated by the script.
    tuple val(query_folder),
        path("$query_folder/errors/*"), optional: true, emit: db_coverage_errors // Output: error files

    script:
    // Build optional CLI flags only when corresponding params are set.
    def bold_flag = params.db_type == 'bold' ? '--bold' : '' // Set --bold flag if using BOLD database
    def db_coverage_toi_limit_arg = params.db_coverage_toi_limit ? "--db-coverage-toi-limit ${params.db_coverage_toi_limit}" : ''
    def db_coverage_max_candidates_arg = params.db_coverage_max_candidates ? "--db-coverage-max-candidates ${params.db_coverage_max_candidates}" : ''
    def gbif_limit_records_arg = params.gbif_limit_records ? "--gbif-limit-records ${params.gbif_limit_records}" : ''
    def gbif_max_occurrence_records_arg = params.gbif_max_occurrence_records ? "--gbif-max-occurrence-records ${params.gbif_max_occurrence_records}" : ''
    def gbif_accepted_status_arg = params.gbif_accepted_status ? "--gbif-accepted-status ${params.gbif_accepted_status}" : ''
    def db_cov_target_min_a_arg = params.db_cov_min_a ? "--db-cov-target-min-a ${params.db_cov_min_a}" : ''
    def db_cov_target_min_b_arg = params.db_cov_min_b ? "--db-cov-target-min-b ${params.db_cov_min_b}" : ''
    def db_cov_related_min_a_arg = params.db_cov_related_min_a ? "--db-cov-related-min-a ${params.db_cov_related_min_a}" : ''
    def db_cov_related_min_b_arg = params.db_cov_related_min_b ? "--db-cov-related-min-b ${params.db_cov_related_min_b}" : ''
    def db_cov_country_missing_a_arg = params.db_cov_country_missing_a ? "--db-cov-country-missing-a ${params.db_cov_country_missing_a}" : ''
    def temp_root_dir_arg = params.temp_root_dir ? "--temp-root ${params.temp_root_dir}" : ''
    def temp_dir_name_arg = params.temp_dir_name ? "--temp-dir-name ${params.temp_dir_name}" : ''
    """
    # Ensure the per-query output folder exists.
    mkdir -p $query_folder

    # Move staged inputs into the query folder to keep upstream outputs intact.
    for item in db_coverage_input/*; do
        [ -e "\$item" ] || continue
        mv "\$item" "$query_folder/"
    done
    rm -r db_coverage_input

    # Run the database coverage Python script
    python /app/scripts/p5_db_coverage.py \
        $query_folder \
        --output-dir ./ \
        --query-fasta ${sequences_file} \
        --metadata-csv ${metadata_file} \
        ${bold_flag} \
        ${db_coverage_toi_limit_arg} \
        ${db_coverage_max_candidates_arg} \
        ${gbif_limit_records_arg} \
        ${gbif_max_occurrence_records_arg} \
        ${gbif_accepted_status_arg} \
        ${db_cov_target_min_a_arg} \
        ${db_cov_target_min_b_arg} \
        ${db_cov_related_min_a_arg} \
        ${db_cov_related_min_b_arg} \
        ${db_cov_country_missing_a_arg} \
        ${temp_root_dir_arg} \
        ${temp_dir_name_arg}
    """
}