[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "taxodactyl-scripts"
version = "1.4.3"
authors = [
	{ name = "Cameron Hyde" }
]
dynamic = ["dependencies"]
requires-python = ">=3.12"

[tool.setuptools.dynamic]
dependencies = {file = ["requirements.txt"]}
